pipeline {
    agent any
    stages {
                              
        stage ('build') {
            
                steps {
                    dir ('Amazon'){                    
                    sh 'mvn clean install'
                    }
                }
                
                    
            }
            
        
        
        stage ('test') {
          
                steps {
                    
                    archiveArtifacts artifacts: 'Amazon/Amazon-Web/target/*.war', followSymlinks: false
                
            }
        }
        
        stage ('run') {
            steps {
                
                    sh 'cp Amazon/Amazon-Web/target/*.war /opt/tomcat/webapps'
                
            }
        }
    }
}
