pipeline {
    agent any
    stages {
                              
        stage ('build') {
            
                steps {
                    dir ('Amazon'){                    
                    sh 'mvn clean install'
                    }
                }
                
                    
            }
            
        
        
        stage ('test') {
          
                steps {
                    
                    archiveArtifacts artifacts: 'Amazon/Amazon-Web/target/*.war', followSymlinks: false
                
            }
        }
        stage ('run') {
        steps {
            dir ('Amazon/Amazon/Amazon-Web'){
                sh 'cp target/*.war /opt/tomcat/webapps'
            }
          }
        }
       
    }
}
